Repository CityOfDetroit/COD-Design-System, pull requests merged in 2023-11, with the labels that each got.

#108 Fix lints in icon element
  src/components/atoms/Icon/Icon.js
Labels: cleanup

#112 Create responsive stacked table
  src/components/atoms/TableBody/TableBody.js
  src/components/atoms/TableCell/TableCell.css
  src/components/atoms/TableCell/TableCell.js
  src/components/atoms/TableCell/_table-cell.scss
  src/components/atoms/TableCellHeader/TableCellHeader.css
  src/components/atoms/TableCellHeader/TableCellHeader.js
  src/components/atoms/TableCellHeader/_table-cell-header.scss
  src/components/atoms/TableHeader/TableHeader.js
  src/components/atoms/TableHeader/_table-header.scss
  src/components/atoms/TableRow/TableRow.js
  src/components/atoms/TableRow/_table-row.scss
  src/components/organisms/Table/Table.js
  src/scss/mixins/_table.scss
  src/scss/themed-bootstrap.scss
  src/shared/js/utilities.js
  src/shared/themed-bootstrap.css
  src/shared/themed-bootstrap.css.map
  src/stories/table.stories.js
Labels: enhancement, a11y

#111 Use table HTML elements for a11y
  src/components/atoms/TableBody/TableBody.css
  src/components/atoms/TableBody/TableBody.js
  src/components/atoms/TableCell/TableCell.css
  src/components/atoms/TableCell/TableCell.js
  src/components/atoms/TableCell/_table-cell.scss
  src/components/atoms/TableCellHeader/TableCellHeader.css
  src/components/atoms/TableCellHeader/TableCellHeader.js
  src/components/atoms/TableCellHeader/_table-cell-header.scss
  src/components/atoms/TableHeader/TableHeader.css
  src/components/atoms/TableHeader/TableHeader.js
  src/components/atoms/TableHeader/_table-header.scss
  src/components/atoms/TableRow/TableRow.css
  src/components/atoms/TableRow/TableRow.js
  src/components/atoms/TableRow/_table-row.scss
  src/components/organisms/Table/Table.js
  src/scss/mixins/_table.scss
  src/scss/themed-bootstrap.scss
  src/shared/js/utilities.js
  src/shared/themed-bootstrap.css
  src/shared/themed-bootstrap.css.map
  src/stories/table.stories.js
Labels: a11y

#117 Fixing a11y plugin typo.
  .storybook/main.js
Labels: bug, a11y

#103 Support action buttons in UXDS
  src/components/atoms/Clickable/Clickable.css
  src/components/atoms/Clickable/Clickable.js
  src/components/atoms/Clickable/cod-clickable.js
  src/components/organisms/Card/Card.css
  src/components/organisms/Card/Card.js
  src/stories/clickable.stories.js
Labels: enhancement

#118 1.0.10
  CHANGELOG.md
  build/assets/js/main.js
  package.json
  src/index.js
Labels: documentation, cleanup
