Repository CityOfDetroit/COD-Design-System, pull requests merged in 2024-03, with the labels that each got.

#140 Mixins for handling observed attributes & CSS classes
  build/assets/js/main.js
  src/components/atoms/TableBody/TableBody.js
  src/components/atoms/TableCell/TableCell.js
  src/components/atoms/TableCellHeader/TableCellHeader.js
  src/components/atoms/TableHeader/TableHeader.js
  src/components/atoms/TableRow/TableRow.js
  src/components/organisms/Table/Table.js
  src/index.js
  src/shared/js/observed-attribute-mixin.js
  src/shared/js/utilities.js
Labels: bug, enhancement, cleanup

#176 Adding Slider component.
  build/assets/js/main.js
  src/components/organisms/ImgSlider/ImgSlider.css
  src/components/organisms/ImgSlider/ImgSlider.js
  src/components/organisms/ImgSlider/cod-img-slider.js
  src/index.js
  src/stories/assets/example-image.svg
  src/stories/assets/example-image2.svg
  src/stories/imgslider.stories.js
Labels: enhancement

#177 1.0.17
  CHANGELOG.md
  package.json
Labels: documentation, cleanup

#172 Map.panel
  build/assets/js/main.js
  build/assets/js/runtime.js
  build/assets/js/vendors.babel.js
  build/assets/js/vendors.maplibre-gl.js
  src/components/atoms/Button/Button.css
  src/components/organisms/Map/Map.css
  src/components/organisms/Map/Map.js
  src/stories/button.stories.js
  src/stories/map.stories.js
Labels: enhancement

#185 Prevent hypothetical XSS
  src/components/atoms/Icon/Icon.js
Labels: bug

#179 Leverage slots in accordion header
  src/components/atoms/AccordionHeader/AccordionHeader.css
  src/components/atoms/AccordionHeader/AccordionHeader.js
  src/stories/accordion.stories.js
Labels: enhancement

#184 Create basic calendar component
  .eslintrc.yml
  package.json
  src/components/organisms/Calendar/Calendar.css
  src/components/organisms/Calendar/Calendar.js
  src/components/organisms/Calendar/cod-calendar.js
  src/stories/calendar.stories.js
  yarn.lock
Labels: enhancement

#186 Support event filters in calendar component
  src/components/organisms/Calendar/Calendar.js
  src/stories/calendar.stories.js
Labels: enhancement

#187 Support custom event/filter background colors
  src/components/organisms/Calendar/Calendar.js
  src/stories/calendar.stories.js
Labels: enhancement

#191 Adding icons to icon component.
  build/assets/js/main.js
  build/assets/js/runtime.js
  build/assets/js/vendors.babel.js
  build/assets/js/vendors.maplibre-gl.js
  src/components/atoms/Icon/Icon.js
  src/stories/icon.stories.js
Labels: enhancement
