Repository CityOfDetroit/COD-Design-System, pull requests merged in 2024-02, with the labels that each got.

#148 Feature.147
  .yarn/cache/bootstrap-icons-npm-1.10.4-da897c241e-d76333e46d.zip
  build/assets/js/main.js
  build/assets/js/vendors.bootstrap-icons.js
  build/index.html
  package.json
  src/components/atoms/Alert/Alert.js
  yarn.lock
Labels: dependencies, cleanup

#150 Setting up map component modes, fixing dev conflicts.
  build/assets/js/main.js
  build/assets/js/runtime.js
  build/assets/js/vendors.maplibre-gl.js
  build/index.html
  package.json
  src/components/organisms/Map/Map.js
  src/components/organisms/Map/cod-map.js
  src/index.js
  src/stories/map.stories.js
Labels: enhancement, tests

#157 Add icons for documents projects, wikis, and discounts
  src/components/atoms/Icon/Icon.js
  src/stories/icon.stories.js
Labels: enhancement

#159 1.0.14
  CHANGELOG.md
  build/assets/js/main.js
  package.json
Labels: cleanup

#158 Create action button component
  src/components/atoms/ActionButton/ActionButton.css
  src/components/atoms/ActionButton/ActionButton.js
  src/components/atoms/ActionButton/cod-action-button.js
  src/components/atoms/Clickable/Clickable.css
  src/components/atoms/Clickable/Clickable.js
  src/components/atoms/Clickable/cod-clickable.js
  src/components/organisms/Card/Card.css
  src/components/organisms/Card/Card.js
  src/stories/actionbutton.stories.js
  src/stories/clickable.stories.js
Labels: enhancement

#160 Implement "ARPA" buttons (renamed Info Buttons)
  src/components/atoms/InfoButton/InfoButton.css
  src/components/atoms/InfoButton/InfoButton.js
  src/components/atoms/InfoButton/cod-info-button.js
  src/stories/infobutton.stories.js
Labels: enhancement

#161 1.0.15
  CHANGELOG.md
  build/assets/js/main.js
  build/assets/js/runtime.js
  build/assets/js/vendors.babel.js
  build/assets/js/vendors.maplibre-gl.js
  package.json
  src/index.js
Labels: cleanup

#165 Fix header background height
  src/scss/mixins/_table.scss
  src/shared/themed-bootstrap.css
  src/shared/themed-bootstrap.css.map
  src/stories/table.stories.js
Labels: bug
