Repository CityOfDetroit/COD-Design-System, pull requests merged in 2024-04, with the labels that each got.

#195 Fixing zoom and center on map.
  build/assets/js/main.js
  src/components/organisms/Map/Map.js
  src/stories/map.stories.js
Labels: bug

#196 Adding missing icons for D6 map.
  build/assets/js/main.js
  src/components/atoms/Icon/Icon.js
  src/stories/icon.stories.js
Labels: enhancement

#192 1.0.19
  CHANGELOG.md
  package.json
Labels: documentation, cleanup

#193 Update UXDS to match detroitmi starterkit themes
  .yarn/cache/sass-npm-1.62.0-bf9dbdfb5f-d5f606aa25.zip
  build/assets/js/main.js
  package.json
  scripts/compile_bootstrap.sh
  src/scss/_bootstrap-variables.scss
  src/scss/_detroitmi-bootstrap-base.scss
  src/scss/_detroitmi-maps.scss
  src/scss/themed-bootstrap.scss
  src/shared/themed-bootstrap.css
  src/shared/themed-bootstrap.css.map
  src/stories/button.stories.js
  yarn.lock
Labels: enhancement, cleanup

#203 Feature.197
  build/assets/js/main.js
  src/components/organisms/Map/Map.js
  src/stories/map.stories.js
Labels: enhancement

#204 1.0.20
  CHANGELOG.md
  package.json
Labels: documentation

#206 Resolve more ESLint errors
  package.json
  src/components/atoms/AccordionBody/AccordionBody.js
  src/components/atoms/AccordionItem/AccordionItem.js
  src/components/atoms/Alert/Alert.js
  src/components/atoms/Badge/Badge.js
  src/components/atoms/Breadcrumb/Breadcrumb.js
  src/components/atoms/CardBody/CardBody.js
  src/components/atoms/CardFooter/CardFooter.js
  src/components/atoms/CardHeader/CardHeader.js
  src/components/atoms/CardOverlay/CardOverlay.js
  src/components/atoms/CarouselCaption/CarouselCaption.js
  src/components/atoms/CarouselItem/CarouselItem.js
  src/components/atoms/Container/Container.js
  src/components/atoms/DropdownMenu/DropdownMenu.js
  src/components/atoms/FormCheck/FormCheck.js
  src/components/atoms/FormControl/FormControl.js
  src/components/atoms/FormLabel/FormLabel.js
  src/components/atoms/FormSelect/FormSelect.js
  src/components/atoms/Image/Image.js
  src/components/atoms/ListGroupItem/ListGroupItem.js
  src/components/atoms/Loader/Loader.js
  src/components/atoms/ModalBody/ModalBody.js
  src/components/atoms/ModalFooter/ModalFooter.js
  src/components/atoms/ModalHeader/ModalHeader.js
  src/components/atoms/PaginationItem/PaginationItem.js
  src/components/atoms/Progress/Progress.js
  src/components/atoms/Range/Range.js
  src/components/atoms/Spinner/Spinner.js
  src/components/atoms/TableBody/TableBody.js
  src/components/atoms/TableCell/TableCell.js
  src/components/atoms/TableCellHeader/TableCellHeader.js
  src/components/atoms/TableHeader/TableHeader.js
  src/components/atoms/TableRow/TableRow.js
  src/components/molecules/Accordion/Accordion.js
  src/components/molecules/ButtonGroup/ButtonGroup.js
  src/components/molecules/FormCheckGroup/FormCheckGroup.js
  src/components/molecules/ListGroup/ListGroup.js
  src/components/molecules/Pagination/Pagination.js
  src/components/organisms/Carousel/Carousel.js
  src/components/organisms/Form/Form.js
  src/components/organisms/Geocoder/Geocoder.js
  src/components/organisms/Map/Map.js
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Offcanvas/Offcanvas.js
  src/components/organisms/Table/Table.js
  src/stories/badge.stories.js
  src/stories/button.stories.js
  src/stories/container.stories.js
  src/stories/formcheck.stories.js
  src/stories/formcontrol.stories.js
  src/stories/formselect.stories.js
  src/stories/range.stories.js
  yarn.lock
Labels: bug, cleanup
